### ISSUE TITLE
VB -> C#: Incorrect conversion for interface readonly property

### ISSUE THREAD

**Issue by mrmonday** [icsharpcode/CodeConverter#270]
### Input code
```vbnet
Public Interface Foo
    ReadOnly Property Something() As String
End Interface
```

### Erroneous output
```c#
public interface Foo
{
    string Something { get; private set; }
}
```

### Expected output
```c#
public interface Foo
{
    string Something { get; }
}
```

### Details
Product in use: VS extension

Version in use: e.g. 6.6.0

**Comment by GrahamTheCoder** [comment]
I've erred on the side of caution when fixing https://github.com/icsharpcode/CodeConverter/issues/237
To improve this we'd need to find usages of the implicit backing field variable and take it into account here:
https://github.com/icsharpcode/CodeConverter/commit/13cd01b937cf9a968049f5488f58fc2d9831ff80#diff-efcb0f9eb87a44613f68d268a25cb12dR456

**Comment by mrmonday** [comment]
This actually gives a compilation error, which is why I reported it - sorry I forgot to include that in the report:

https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0275

**Comment by GrahamTheCoder** [comment]
Ah sorry, I missed the fact it was on an interface. Yup that's a bug right there. It will have been introduced in #237, so should be an easy fix when looking through that.
